// Wave params [frequency, amplitude, phase] for organic bumpy shapes
// Must be shared between physics (Planet.ts) and visuals (PlanetGenerator.ts)
export const SHAPE_WAVES = {
    asteroid: [[3, 0.14, 0.80], [5, 0.07, 1.50], [7, 0.04, 0.30]],
    meteorite: [[4, 0.09, 0.60], [6, 0.05, 1.00]],
};
export const PLANETS = [
    {
        id: 0,
        name: 'Asteroide',
        texture: 'asteroid',
        radius: 18,
        points: 1,
        glowColor: 0xccbbaa,
        glowIntensity: 0.35,
        nextPlanetId: 1,
        shape: 'asteroid',
    },
    {
        id: 1,
        name: 'Mercuri',
        texture: 'mercury',
        radius: 24,
        points: 2,
        glowColor: 0xaaaaaa,
        glowIntensity: 0.4,
        nextPlanetId: 2,
        shape: 'meteorite',
    },
    {
        id: 2,
        name: 'Venus',
        texture: 'venus',
        radius: 32,
        points: 4,
        glowColor: 0xffcc66,
        glowIntensity: 0.5,
        nextPlanetId: 3,
    },
    {
        id: 3,
        name: 'Terra',
        texture: 'earth',
        radius: 40,
        points: 8,
        glowColor: 0x44aaff,
        glowIntensity: 0.6,
        nextPlanetId: 4,
    },
    {
        id: 4,
        name: 'Mart',
        texture: 'mars',
        radius: 48,
        points: 12,
        glowColor: 0xff4422,
        glowIntensity: 0.6,
        nextPlanetId: 5,
    },
    {
        id: 5,
        name: 'Júpiter',
        texture: 'jupiter',
        radius: 62,
        points: 18,
        glowColor: 0xffaa44,
        glowIntensity: 0.7,
        nextPlanetId: 6,
    },
    {
        id: 6,
        name: 'Saturn',
        texture: 'saturn',
        radius: 74,
        points: 25,
        glowColor: 0xddcc88,
        glowIntensity: 0.7,
        nextPlanetId: 7,
        hasRings: true,
    },
    {
        id: 7,
        name: 'Urà',
        texture: 'uranus',
        radius: 86,
        points: 33,
        glowColor: 0x88ffee,
        glowIntensity: 0.8,
        nextPlanetId: 8,
    },
    {
        id: 8,
        name: 'Neptú',
        texture: 'neptune',
        radius: 98,
        points: 42,
        glowColor: 0x4466ff,
        glowIntensity: 0.8,
        nextPlanetId: 9,
        hasRings: true,
    },
    {
        id: 9,
        name: 'Sol',
        texture: 'sun',
        radius: 118,
        points: 100,
        glowColor: 0xffff00,
        glowIntensity: 1.0,
        nextPlanetId: null,
    },
];
export const MAX_DROP_PLANET_ID = 3;
export const SUPERNOVA_PLANET_ID = 10;
export const SUPERNOVA_SCORE_THRESHOLD = 500;
// Keep for backwards compat
export const EXPLOSION_SCORE_THRESHOLD = SUPERNOVA_SCORE_THRESHOLD;
PLANETS.push({
    id: SUPERNOVA_PLANET_ID,
    name: 'Supernova',
    texture: 'supernova',
    radius: 36,
    points: 0,
    glowColor: 0xffaa00,
    glowIntensity: 1.0,
    nextPlanetId: null,
});
